# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coap < Formula
  desc "Tool to help testing coap endpoints."
  homepage "https://docs.golioth.io/"
  version "1.2.0-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.0-beta.1/coap-cli_1.2.0-beta.1_macos_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "7381601a303fb320391f5468e51d4be6c0b4ec02156a6b95733ca701a2a922d4"

      def install
        bin.install "coap"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.0-beta.1/coap-cli_1.2.0-beta.1_macos_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6947cd3a558331f2a2e47b611ffe79a537519c91f9a0b81b90a63e0b35ee9dcc"

      def install
        bin.install "coap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.0-beta.1/coap-cli_1.2.0-beta.1_linux_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "84c3b80e8de267657c798cb129a4c2bf09791cfe05c9e6d640b963cadebbb100"

      def install
        bin.install "coap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.0-beta.1/coap-cli_1.2.0-beta.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c5a765ef80abda16b284ad8de59a5d0b8b98c70250aa50fb372bce67d658bd22"

      def install
        bin.install "coap"
      end
    end
  end
end
