# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coap < Formula
  desc "Tool to help testing coap endpoints."
  homepage "https://docs.golioth.io/"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.1/coap-cli_1.2.1_macos_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "a2d6b66aab1682a0f031ccd119b885a8defbb996baf3806d8ade6bf6e0eb3f36"

      def install
        bin.install "coap"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.1/coap-cli_1.2.1_macos_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3865ec5fee2a7227a08dcf854ff210c5d9cd5ddf1c3fad20cc4edb782a3b22a8"

      def install
        bin.install "coap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.1/coap-cli_1.2.1_linux_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "a3cfa37d993c3169b11004341cfe36eb6909425d11da4f7084c5144c7a94839c"

      def install
        bin.install "coap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/golioth-cli-releases/coap-cli/v1.2.1/coap-cli_1.2.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7505dd27f553f1ea5be9d00fb34fbaf80fc0c5c0d1452ad0cd3651a1b4e82afb"

      def install
        bin.install "coap"
      end
    end
  end
end
