# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golioth < Formula
  desc "Tool to help interact with Golioth Platform and with IoT development in general."
  homepage "https://docs.golioth.dev/"
  version "0.13.1"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.13.1/golioth_0.13.1_macos_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "67f44e8d7fb9584284d0ee29dced50d598fbd5cca5e4b671b8ea450074bccfd8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.13.1/golioth_0.13.1_linux_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "80c9257ee03bd3df7255b377e1a0e3a5557db57af853ee12ede2a9701bd0c3fb"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.13.1/golioth_0.13.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "103a0738118a9fcb8cc3252f4024b43d9e175e8cf570449a1c5d832705eda2be"
    end
  end

  def install
    bin.install "goliothctl"
    bin.install "coap"
  end
end
