# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goliothctl < Formula
  desc "Tool to help interact with Golioth Platform and with IoT development in general."
  homepage "https://docs.golioth.dev/"
  version "1.1.0"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/goliothctl/v1.1.0/goliothctl_1.1.0_macos_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "8d8b284530a981410cc3a38edf9d2fa59ae0024fc3be6d9f135566ea4588d790"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/golioth-cli-releases/goliothctl/v1.1.0/goliothctl_1.1.0_linux_64bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "e482ef908b195078c8db4226710f6852aab385e285e18de60340777c09366dcc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/golioth-cli-releases/goliothctl/v1.1.0/goliothctl_1.1.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "dddee8c1ea1fc7c1cd6fc48c02a86f8472713b090dd2417b8b9b3a2aff877f7a"
    end
  end

  def install
    bin.install "goliothctl"
  end
end
