# This file was generated by GoReleaser. DO NOT EDIT.
class Golioth < Formula
  desc "Tool to help interact with Golioth Platform and help with IoT development."
  homepage "https://docs.golioth.dev/"
  version "v0.10.0"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.10.0/golioth_0.10.0_macos_64bit.tar.gz", :using => CurlDownloadStrategy.
    sha256 "df9c74ba9ede5151c3e16ea4a9f51a6d9bdd7882435e256848a3352817c92a41"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.10.0/golioth_0.10.0_linux_64bit.tar.gz", :using => CurlDownloadStrategy.
    sha256 "a55b2918f241b2d1fb73ce7af77200fc25a4559073e9caefa226a4bdb8b28fe6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.10.0/golioth_0.10.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "699cbf3dd1c6ceabb0e270027063bdd22abf67e4fc62a75a8222cfb44f181f9e"
  end

  def install
    bin.install "goliothctl"
    bin.install "gurl"
  end
end
