# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golioth < Formula
  desc "Tool to help interact with Golioth Platform and with IoT development in general."
  homepage "https://docs.golioth.dev/"
  version "0.13.0"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.13.0/golioth_0.13.0_macos_64bit.tar.gz", :using => CurlDownloadStrategy
    sha256 "5e6ee66f114368d7fa3dd7aed7781cb45bb4f4a6e04c8c65557f9a40b114c254"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.13.0/golioth_0.13.0_linux_64bit.tar.gz", :using => CurlDownloadStrategy
    sha256 "500ad3e1dd9535c312af5b61992e55e2a22c7921e252f9b46d0a349a07993ac7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://storage.googleapis.com/golioth-cli-releases/golioth/v0.13.0/golioth_0.13.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "5603a90fcce0b9150b37cae6e1f1a2684cdfceb8c609cac8367283f042e06e38"
  end

  def install
    bin.install "goliothctl"
    bin.install "gurl"
  end
end
